title: calm_peng Blog
email: 
description: >- # this means to ignore newlines until "baseurl:"
  功不唐捐
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calmpeng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: calmpeng/calmpeng.github.io
twitter:
github: calmpeng

paginate: 5
paginate_path: "/:num/"

google_analytics:
comments: false
disqus:

author: calm_peng
author_pic:
author_bio: >-
  24


# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
